ALTER TABLE users DROP COLUMN IF EXISTS access_token;
ALTER TABLE users DROP COLUMN IF EXISTS refresh_token;
ALTER TABLE users DROP COLUMN IF EXISTS token_expiry;
ALTER TABLE users DROP COLUMN IF EXISTS scopes;
