ALTER TABLE users ADD COLUMN IF NOT EXISTS access_token BYTEA NOT NULL DEFAULT ''::bytea;
ALTER TABLE users ADD COLUMN IF NOT EXISTS refresh_token BYTEA;
ALTER TABLE users ADD COLUMN IF NOT EXISTS token_expiry TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS scopes TEXT NOT NULL DEFAULT '';
