# language: en

@sprint-3 @f006 @pipeline @regression
Feature: F-006 Contracts Codegen（Go struct → TS types 自動產生）
  As a 開發者
  I want Go DTO 自動產出 TypeScript interface
  So that 前後端型別同步，CI 可以偵測 drift

  # --- 產出檔案驗證 ---

  Scenario: contracts.generated.ts 存在且有正確標頭
    Given make contracts 已執行
    Then 檔案 web/src/contracts.generated.ts 存在
    And 檔案第一行包含 "Code generated by tygo. DO NOT EDIT."

  Scenario: contracts.generated.ts 包含所有核心 DTO
    Given web/src/contracts.generated.ts 已存在
    Then 檔案包含 interface Settings
    And 檔案包含 interface Draft 或 type Draft
    And 檔案包含 interface Space
    And 檔案包含 interface SentRecord
    And 檔案包含 interface ProfileFact
    And 檔案包含 interface Inbox 或相關 inbox 型別

  # --- 型別轉換正確性 ---

  Scenario: 指標型別轉換為 T | null
    Given Go struct 中有 *string 或 *int 欄位
    When make contracts 執行後
    Then contracts.generated.ts 對應欄位型別為 "T | null"

  Scenario: time.Time 轉換為 string
    Given Go struct 中有 time.Time 欄位
    When make contracts 執行後
    Then contracts.generated.ts 對應欄位型別為 string

  # --- make contracts 指令 ---

  Scenario: make contracts 可以在本機執行
    Given tygo 已安裝且 tygo.yaml 存在
    When 執行 make contracts
    Then 命令 exit code 為 0
    And web/src/contracts.generated.ts 被更新

  # --- build 整合 ---

  Scenario: web 專案 build 通過（contracts import 正確）
    Given contracts.generated.ts 已存在
    And web/src/contracts.ts 從 contracts.generated re-export
    When 執行 npm run build --prefix web
    Then build 結束 exit code 為 0，無 TypeScript 錯誤

  # --- CI drift 偵測 ---

  Scenario: Go struct 改變但未重產 TS → CI fail
    Given .github/workflows/contracts-drift.yml 存在
    When PR 修改 Go struct 且未重新執行 make contracts
    Then contracts-drift CI job 失敗

  Scenario: Go struct 改變且已重產 TS → CI pass
    Given .github/workflows/contracts-drift.yml 存在
    When PR 修改 Go struct 並執行 make contracts 重新 commit
    Then contracts-drift CI job 通過
