// Code generated by tygo. DO NOT EDIT.
// Source: internal/httpapi/types.go
// Run 'make contracts' to regenerate.
//////////
// source: claude.go


//////////
// source: debug.go


//////////
// source: debug_inject_ws.go


//////////
// source: debug_seed.go


//////////
// source: drafts.go


//////////
// source: extension.go


//////////
// source: types.go
/*
Package httpapi — wire-level DTO types for the React frontend.

This file is the single source of truth for the JSON shapes returned by
the HTTP API. tygo reads this file to generate web/src/contracts.generated.ts.

Rules:
  - Every exported field MUST have a `json:"..."` tag.
  - Fields without a json tag are NOT exported to TypeScript.
  - Use pointer types (*T) for optional / nullable fields → TS `T | null`.
  - time.Time is mapped to `string` (ISO 8601) by tygo.yaml configuration.

Run `make contracts` to regenerate web/src/contracts.generated.ts.
*/

/**
 * Settings is the global per-user configuration returned by GET /api/settings
 * and emitted in WebSocket settings_updated events.
 */
export interface Settings {
  auto_mode: boolean;
  freshness_window_minutes: number /* int */;
  debug_mode: boolean;
  blocked_keywords: string;
  reply_only_when_mentioned: boolean;
  safety_rails_enabled: boolean;
  safety_rules: { [key: string]: boolean};
}
/**
 * Space is one row returned by GET /api/spaces — a Google Chat space with
 * its per-channel settings.
 */
export interface Space {
  space_key: string;
  space_name: string;
  enabled: boolean;
  mention_only: boolean;
  auto_mode_override: string; // "inherit" | "always_on" | "always_off"
  safety_rails_override: string; // "inherit" | "disabled"
  blocked_keywords: string[];
  message_count: number /* int */;
  last_message_at?: string /* ISO 8601 */;
}
/**
 * ContextMessage is a single message in the conversation context bundled with
 * a Draft in the approval queue.
 */
export interface ContextMessage {
  sender_name: string;
  content: string;
  created_at: string /* ISO 8601 */;
  is_me: boolean;
}
/**
 * DraftDebugInfo carries optional debug information attached to a Draft when
 * DebugMode is enabled in Settings.
 */
export interface DraftDebugInfo {
  categorize_reason?: string;
  confidence?: number /* float32 */;
  context_source?: string;
  model?: string;
}
/**
 * Draft is one pending approval item returned by GET /api/drafts. It bundles
 * the AI-generated reply with enough context (space / sender / original message)
 * for the ApprovalsPage to render a complete ApprovalCard.
 */
export interface Draft {
  id: number /* int64 */;
  space_id: string;
  space_name: string;
  sender_id: string;
  sender_name: string;
  original_message: string;
  context_messages: ContextMessage[];
  draft_content: string;
  category: string;
  debug?: DraftDebugInfo;
  created_at: string /* ISO 8601 */;
  message_id: number /* int64 */;
  safety_flags: string[];
  safety_trigger_reason: string;
  safety_overridden_by?: string;
}
/**
 * SentRecord is one row returned by GET /api/sent — a successfully delivered
 * message in the Sent Log.
 */
export interface SentRecord {
  id: string;
  space_id: string;
  space_name: string;
  sender_id: string;
  sender_name: string;
  trigger_message: string;
  sent_content: string;
  mode: string; // "approved" | "auto"
  edited_by_user: boolean;
  category: string;
  sent_at: string /* ISO 8601 */;
}
/**
 * ProfileFact is one piece of user-curated personal information the AI skill
 * can consult. Returned by GET /api/claude/profile.
 */
export interface ProfileFact {
  id: number /* int64 */;
  key: string;
  value: string;
  visibility: string; // "public" | "private" | "secret"
  note: string;
  updated_at: string /* ISO 8601 */;
}
/**
 * Inbox is one item in the real-time inbox — a message together with its
 * latest pending draft (if any). Emitted via WebSocket draft_created events
 * and used by the approval queue.
 */
export interface Inbox {
  id: number /* int64 */;
  space_id: string;
  space_name: string;
  sender_id: string;
  sender_name: string;
  original_message: string;
  context_messages: ContextMessage[];
  draft_content: string;
  category: string;
  debug?: DraftDebugInfo;
  created_at: string /* ISO 8601 */;
  message_id: number /* int64 */;
  safety_flags: string[];
  safety_trigger_reason: string;
  safety_overridden_by?: string;
}

//////////
// source: ws.go

/**
 * Ingestor is the subset of worker.ChatProcessor that httpapi needs.
 * Declared as an interface so httpapi doesn't hard-depend on worker.
 */
export type Ingestor = any;
