// Package hub is an in-memory pub-sub used to push updates from the backend
// to live WebSocket clients (UI + extension). Single-user, single-process MVP
// so we don't need a broker; a map of channels with a mutex is enough.
package hub

import (
	"encoding/json"
	"sync"
)

// UIEvent is delivered to web-UI WebSocket clients.
//
// Type values:
//   - Legacy (notification-only): "inbox_changed" | "settings_changed" | "spaces_changed"
//   - New (payload-bearing):      "draft_created" | "draft_removed" | "settings_updated"
//   - F-013:                      "pending_changed"
//
// Sprint 3 will remove the legacy types; during Sprint 2 both coexist for
// backward-compat (ApprovalsPage still uses inbox_changed via SWR refetch).
type UIEvent struct {
	Type      string          `json:"type"`
	Draft     json.RawMessage `json:"draft,omitempty"`      // for draft_created: full draft object
	DraftID   string          `json:"draft_id,omitempty"`   // for draft_removed: string to allow symbolic IDs
	Settings  json.RawMessage `json:"settings,omitempty"`   // for settings_updated
	Reason    string          `json:"reason,omitempty"`     // for pending_changed: new_message|skipped|unskipped|drafted
	MessageID string          `json:"message_id,omitempty"` // for pending_changed: identifies the affected message
}

// ExtEvent is delivered to extension WebSocket clients.
type ExtEvent struct {
	Type     string   `json:"type"`                // "pending" | "refresh_spaces" | "batchexecute_sender_search" | "reaction_request"
	Pending  any      `json:"pending,omitempty"`   // approved draft row (same shape as /api/ext/pending)
	SpaceIDs []string `json:"space_ids,omitempty"` // for refresh_spaces: raw space ids to look up via get_group

	// batchexecute_sender_search: tells the extension to call Chat's
	// SBNmJb RPC from the browser (where cookies are valid) so the
	// response flows back through the normal XHR hook → raw path.
	Ldap     string `json:"ldap,omitempty"`
	BeforeMs int64  `json:"before_ms,omitempty"`
	PageSize int    `json:"page_size,omitempty"`

	// reaction_request: ask the extension to POST an emoji reaction to Chat's
	// /api/update_reaction (same pattern as create_message). ReqID is the
	// caller-supplied id used to correlate the eventual reaction_result.
	ReqID     string `json:"req_id,omitempty"`
	SpaceKey  string `json:"space_key,omitempty"`
	ThreadKey string `json:"thread_key,omitempty"`
	MessageID string `json:"message_id,omitempty"`
	Emoji     string `json:"emoji,omitempty"`
	Action    string `json:"action,omitempty"` // "add" | "remove"

	// sync_history_scan: tell the extension to start scanning a space's
	// history via batchexecute and POST batches to /api/extension/sync-history.
	JobID string `json:"job_id,omitempty"`

	// proxy_request: tell the extension to run an XHR in chat.google.com's
	// origin (so Chrome integrity / cookies attach automatically) and report
	// the response back via "proxy_response". Backend constructs everything
	// — URL, method, headers, body — so extension stays a dumb HTTP relay.
	ProxyURL     string            `json:"proxy_url,omitempty"`
	ProxyMethod  string            `json:"proxy_method,omitempty"`
	ProxyHeaders map[string]string `json:"proxy_headers,omitempty"`
	ProxyBody    string            `json:"proxy_body,omitempty"`
}

// ProxyResult is the extension's reply to a proxy_request.
type ProxyResult struct {
	OK         bool              `json:"ok"`
	Error      string            `json:"error,omitempty"`
	Status     int               `json:"status,omitempty"`
	Response   string            `json:"response,omitempty"`
	RespHeader map[string]string `json:"resp_header,omitempty"`
}

type Hub struct {
	mu  sync.RWMutex
	ui  map[chan UIEvent]struct{}
	ext map[chan ExtEvent]struct{}

	// dispatchedDrafts tracks draft IDs that have already been pushed to
	// some extension WS client. Guards against double-send when the user
	// has multiple Chat tabs open (each tab's content.js connects its own
	// WS and would otherwise each dispatch the same draft to create_message).
	// Cleared in ReleaseDraft once the extension reports success/failure.
	// In-memory only; cleared on restart (which is fine — new approved
	// drafts will be re-pushed after a reconnect).
	dispatchedMu sync.Mutex
	dispatched   map[int64]struct{}

	// Pending reaction requests waiting for the extension to report back.
	// Keyed by req_id (generated by /api/reactions). The HTTP handler creates
	// a channel, publishes the reaction_request event, then blocks on the
	// channel until either the extension replies (via ws "reaction_result")
	// or the handler times out.
	reactionMu      sync.Mutex
	reactionWaiters map[string]chan ReactionResult

	proxyMu      sync.Mutex
	proxyWaiters map[string]chan ProxyResult
}

// ReactionResult is the terminal state of a reaction_request, delivered back
// from the extension over WS and dispatched to whoever is awaiting on it.
type ReactionResult struct {
	OK     bool   `json:"ok"`
	Error  string `json:"error,omitempty"`
	Status int    `json:"status,omitempty"` // HTTP status of the chat.google.com call (best-effort)
}

func New() *Hub {
	return &Hub{
		ui:         make(map[chan UIEvent]struct{}),
		ext:        make(map[chan ExtEvent]struct{}),
		dispatched:      make(map[int64]struct{}),
		reactionWaiters: make(map[string]chan ReactionResult),
		proxyWaiters:    make(map[string]chan ProxyResult),
	}
}

// AwaitProxy registers a waiter for the given proxy req_id.
func (h *Hub) AwaitProxy(reqID string) (<-chan ProxyResult, func()) {
	ch := make(chan ProxyResult, 1)
	h.proxyMu.Lock()
	h.proxyWaiters[reqID] = ch
	h.proxyMu.Unlock()
	return ch, func() {
		h.proxyMu.Lock()
		delete(h.proxyWaiters, reqID)
		h.proxyMu.Unlock()
	}
}

// CompleteProxy dispatches a proxy_response to whoever is waiting on reqID.
func (h *Hub) CompleteProxy(reqID string, res ProxyResult) bool {
	if reqID == "" {
		return false
	}
	h.proxyMu.Lock()
	ch, ok := h.proxyWaiters[reqID]
	h.proxyMu.Unlock()
	if !ok {
		return false
	}
	select {
	case ch <- res:
		return true
	default:
		return false
	}
}

// ProxyRequest broadcasts a proxy_request to extension clients. The extension
// is responsible for running the XHR inside chat.google.com's origin and
// returning a proxy_response with the matching req_id.
func (h *Hub) ProxyRequest(reqID, url, method string, headers map[string]string, body string) {
	if reqID == "" || url == "" {
		return
	}
	if method == "" {
		method = "GET"
	}
	h.PublishExt(ExtEvent{
		Type:         "proxy_request",
		ReqID:        reqID,
		ProxyURL:     url,
		ProxyMethod:  method,
		ProxyHeaders: headers,
		ProxyBody:    body,
	})
}

// AwaitReaction registers a waiter for the given reqID. Caller must drain or
// abandon the returned channel; the cleanup func removes the waiter from the
// map. Send is non-blocking on the hub side so a dropped channel never stalls
// the WS reader.
func (h *Hub) AwaitReaction(reqID string) (<-chan ReactionResult, func()) {
	ch := make(chan ReactionResult, 1)
	h.reactionMu.Lock()
	h.reactionWaiters[reqID] = ch
	h.reactionMu.Unlock()
	return ch, func() {
		h.reactionMu.Lock()
		delete(h.reactionWaiters, reqID)
		h.reactionMu.Unlock()
	}
}

// CompleteReaction is called by the WS reader when a reaction_result frame
// arrives. Returns true if a waiter consumed it.
func (h *Hub) CompleteReaction(reqID string, res ReactionResult) bool {
	if reqID == "" {
		return false
	}
	h.reactionMu.Lock()
	ch, ok := h.reactionWaiters[reqID]
	h.reactionMu.Unlock()
	if !ok {
		return false
	}
	select {
	case ch <- res:
		return true
	default:
		return false
	}
}

// ClaimDraft returns true if this is the first caller to claim the given
// draftID since the last ReleaseDraft. Use this to guard pending-broadcast
// so the draft gets pushed to exactly one extension tab even when the user
// has multiple Chat windows open sharing the same backend.
func (h *Hub) ClaimDraft(draftID int64) bool {
	if draftID <= 0 {
		return true
	}
	h.dispatchedMu.Lock()
	defer h.dispatchedMu.Unlock()
	if _, ok := h.dispatched[draftID]; ok {
		return false
	}
	h.dispatched[draftID] = struct{}{}
	return true
}

// ReleaseDraft lets a draft be pushed again. Call when the extension reports
// a terminal state (sent / failed) so retries after failures can still work.
func (h *Hub) ReleaseDraft(draftID int64) {
	if draftID <= 0 {
		return
	}
	h.dispatchedMu.Lock()
	delete(h.dispatched, draftID)
	h.dispatchedMu.Unlock()
}

// SubscribeUI returns a buffered channel and an unsubscribe func. The channel
// must be drained by the caller; events are dropped (non-blocking send) if the
// buffer is full, so a slow client can never stall a publisher.
func (h *Hub) SubscribeUI() (<-chan UIEvent, func()) {
	ch := make(chan UIEvent, 16)
	h.mu.Lock()
	h.ui[ch] = struct{}{}
	h.mu.Unlock()
	return ch, func() {
		h.mu.Lock()
		delete(h.ui, ch)
		h.mu.Unlock()
		close(ch)
	}
}

func (h *Hub) SubscribeExt() (<-chan ExtEvent, func()) {
	ch := make(chan ExtEvent, 32)
	h.mu.Lock()
	h.ext[ch] = struct{}{}
	h.mu.Unlock()
	return ch, func() {
		h.mu.Lock()
		delete(h.ext, ch)
		h.mu.Unlock()
		close(ch)
	}
}

func (h *Hub) PublishUI(ev UIEvent) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	for ch := range h.ui {
		select {
		case ch <- ev:
		default:
		}
	}
}

func (h *Hub) PublishExt(ev ExtEvent) {
	h.mu.RLock()
	defer h.mu.RUnlock()
	for ch := range h.ext {
		select {
		case ch <- ev:
		default:
		}
	}
}

// convenience helpers — keep the shape consistent at call sites.

// --- Legacy notification-only helpers (backward compat; Sprint 3 will clean up) ---

func (h *Hub) InboxChanged()    { h.PublishUI(UIEvent{Type: "inbox_changed"}) }
func (h *Hub) SettingsChanged() { h.PublishUI(UIEvent{Type: "settings_changed"}) }
func (h *Hub) SpacesChanged()   { h.PublishUI(UIEvent{Type: "spaces_changed"}) }

// --- New payload-bearing helpers ---

// DraftCreated broadcasts a draft_created event containing the full draft
// object as JSON. d must be JSON-serialisable.
func (h *Hub) DraftCreated(d any) {
	raw, err := json.Marshal(d)
	if err != nil {
		return
	}
	h.PublishUI(UIEvent{Type: "draft_created", Draft: raw})
}

// DraftRemoved broadcasts a draft_removed event. id is kept as a string so
// it can carry either a numeric DB id or a symbolic test id like "draft-ws-new".
func (h *Hub) DraftRemoved(id string) {
	if id == "" {
		return
	}
	h.PublishUI(UIEvent{Type: "draft_removed", DraftID: id})
}

// SettingsUpdated broadcasts a settings_updated event containing the full
// settings object as JSON. s must be JSON-serialisable.
func (h *Hub) SettingsUpdated(s any) {
	raw, err := json.Marshal(s)
	if err != nil {
		return
	}
	h.PublishUI(UIEvent{Type: "settings_updated", Settings: raw})
}

// ActivityBump is shorthand for "a new message just arrived" — the inbox
// obviously needs to refresh, and so does the Channel 設定 list (a
// previously-silent space may have just re-entered the 30-minute window).
func (h *Hub) ActivityBump() {
	h.InboxChanged()
	h.SpacesChanged()
}

func (h *Hub) Pending(item any) { h.PublishExt(ExtEvent{Type: "pending", Pending: item}) }

// PendingChanged broadcasts a pending_changed event to UI clients.
// reason is one of: new_message, skipped, unskipped, drafted.
// messageID is the message_key of the affected message.
func (h *Hub) PendingChanged(reason, messageID string) {
	h.PublishUI(UIEvent{Type: "pending_changed", Reason: reason, MessageID: messageID})
}

func (h *Hub) RefreshSpaces(spaceIDs []string) {
	if len(spaceIDs) == 0 {
		return
	}
	h.PublishExt(ExtEvent{Type: "refresh_spaces", SpaceIDs: spaceIDs})
}

// ReactionRequest broadcasts a reaction_request to extension clients. The
// extension is responsible for replaying the captured update_reaction template
// (see inject-main.js) using the user's own Chat session.
func (h *Hub) ReactionRequest(reqID, spaceKey, threadKey, messageID, emoji, action string) {
	if reqID == "" || spaceKey == "" || messageID == "" || emoji == "" {
		return
	}
	if action == "" {
		action = "add"
	}
	h.PublishExt(ExtEvent{
		Type:      "reaction_request",
		ReqID:     reqID,
		SpaceKey:  spaceKey,
		ThreadKey: threadKey,
		MessageID: messageID,
		Emoji:     emoji,
		Action:    action,
	})
}

// SyncHistoryScan asks the extension to start a sync-history scan for the
// given space. Pair with /api/extension/sync-history/start (which created the
// job) — the extension will POST batches against that job_id.
func (h *Hub) SyncHistoryScan(jobID, spaceKey string) {
	if jobID == "" {
		return
	}
	h.PublishExt(ExtEvent{
		Type:     "sync_history_scan",
		JobID:    jobID,
		SpaceKey: spaceKey,
	})
}

func (h *Hub) RequestSenderSearch(ldap string, beforeMs int64, pageSize int) {
	if ldap == "" {
		return
	}
	h.PublishExt(ExtEvent{
		Type:     "batchexecute_sender_search",
		Ldap:     ldap,
		BeforeMs: beforeMs,
		PageSize: pageSize,
	})
}
